name: Smart Contract CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'onchain/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'onchain/**'

jobs:
  smart-contract-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./onchain

    steps:
    - uses: actions/checkout@v3

    - name: Set up Scarb
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
        scarb --version

    - name: Cache Scarb dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.scarb
          target/
        key: ${{ runner.os }}-scarb-${{ hashFiles('**/Scarb.toml') }}
        restore-keys: |
          ${{ runner.os }}-scarb-

    - name: Check Cairo formatting
      run: |
        scarb fmt --check

    - name: Build smart contracts
      run: |
        scarb build
        
    - name: Run tests
      run: |
        scarb test

    - name: Run security checks
      run: |
        # Basic security checks for Cairo contracts
        echo "Running security checks..."
        # Check for common security patterns
        ! find . -type f -name "*.cairo" -exec grep -l "assert_not_zero" {} \;
        ! find . -type f -name "*.cairo" -exec grep -l "unsafe_" {} \;

    - name: Upload compilation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiled-contracts
        path: target/
        retention-days: 7

    - name: Report Status
      if: always()
      run: |
        echo "CI Process Complete"
        echo "Compilation Status: ${{ job.status }}"